config/routes.rb
Immo::Application.routes.draw do
   root 'home#index'
  resources :acquereurs

  get "articles/search" =>"articles#find_last"
  resources :articles do
  end

end

app/models/acquereur.rb
class Acquereur < ActiveRecord::Base
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/acquereurs_controller.rb
class AcquereursController < ApplicationController
  before_action :set_acquereur, only: [:show, :edit, :update, :destroy]

  # GET /acquereurs
  # GET /acquereurs.json
  def index
    @acquereurs = Acquereur.all
  end

  # GET /acquereurs/1
  # GET /acquereurs/1.json
  def show
  end

  # GET /acquereurs/new
  def new
    @acquereur = Acquereur.new
  end

  # GET /acquereurs/1/edit
  def edit
  end

  # POST /acquereurs
  # POST /acquereurs.json
  def create
    @acquereur = Acquereur.new(acquereur_params)

    respond_to do |format|
      if @acquereur.save
        format.html { redirect_to @acquereur, notice: 'Acquereur was successfully created.' }
        format.json { render action: 'show', status: :created, location: @acquereur }
      else
        format.html { render action: 'new' }
        format.json { render json: @acquereur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acquereurs/1
  # PATCH/PUT /acquereurs/1.json
  def update
    respond_to do |format|
      if @acquereur.update(acquereur_params)
        format.html { redirect_to @acquereur, notice: 'Acquereur was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @acquereur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acquereurs/1
  # DELETE /acquereurs/1.json
  def destroy
    @acquereur.destroy
    respond_to do |format|
      format.html { redirect_to acquereurs_url }
      format.json { head :no_content }
    end
  end

  def findfirst
    @acquereurs = Acquereur.first
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acquereur
      @acquereur = Acquereur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acquereur_params
      params.require(:acquereur).permit(:nom, :prenom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @articles = Article.order(nom: :desc) 
      end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end

  end


    def find_last
      @article = Article.last
      
    end

 #private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:nom, :titre, :contenu, :price, :jour, :age)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/acquereurs_helper.rb
module AcquereursHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/acquereurs/_form.html.erb
<%= form_for(@acquereur) do |f| %>
  <% if @acquereur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@acquereur.errors.count, "error") %> prohibited this acquereur from being saved:</h2>

      <ul>
      <% @acquereur.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :Nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :Prenom %><br>
    <%= f.text_field :prenom %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acquereurs/edit.html.erb
<h1>Editing acquereur</h1>

<%= render 'form' %>

<%= link_to 'Show', @acquereur %> |
<%= link_to 'Back', acquereurs_path %>

app/views/acquereurs/index.html.erb
<h1>Listing acquereurs</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Prenom</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @acquereurs.each do |acquereur| %>
    <tr>
    <td><%= acquereur.nom.capitalize %></td>
        <td><%= acquereur.prenom.capitalize %></td>
      
        <td><%= link_to 'Show', acquereur %></td>
        <td><%= link_to 'Edit', edit_acquereur_path(acquereur) %></td>
        <td><%= link_to 'Destroy', acquereur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Acquereur', new_acquereur_path %>
<%= link_to 'Accueil', root_path %>
<%= link_to 'first', root_path %>

app/views/acquereurs/new.html.erb
<h1>New acquereur</h1>

<%= render 'form' %>

<%= link_to 'Back', acquereurs_path %>

app/views/acquereurs/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Identifiant:</strong>
  <%= @acquereur.id %>
</p>
<p>
  <strong>Nom:</strong>
  <%= @acquereur.nom %>
</p>
<p>
  <strong>Prénom:</strong>
  <%= @acquereur.prenom %>
</p>
<%= link_to 'Edit', edit_acquereur_path(@acquereur) %> |
<%= link_to 'Back', acquereurs_path %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" >
    <%= f.label :nom %>
    <%= f.text_field :nom   %><br> 
  </div>
  <div class="field">
    <%= f.label :titre %>
    <%= f.text_field :titre, :class =>"rouge" %>
  </div>
  <div class="field">
    <%= f.label :contenu %><br>
    <%= f.text_area :contenu %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_area :price %>
  </div>
    <div class="field">
    <%= f.label :jour %><br>
    <%= f.text_field :jour %>
  </div>
  <div class="field">
    <%= f.label :Age %><br>
    <%= f.text_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_form_search.html.erb
<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:nom, "Search for:") %>
  <%= text_field_tag(article:   :nom) %>
  <%= submit_tag("Search") %>
<% end %>
_____________________________________________________________

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/find_last.html.erb
<h1>Listing articles</h1>
<!-- script pour le debut du chargement -->
  <script type="text/javascript">
  <!--
  //-->
  </script>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Titre</th>
      <th>Contenu</th>
      <th>Price</th>
      <th>Jour</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
   
      <tr>
        <td><%= @article.nom.capitalize %></td>
        <td><%= @article.titre.capitalize %></td>
        <td><%= @article.contenu %></td>
        <td><%= @article.price %></td>
        <td><%= @article.jour %></td>
        <td><%= @article.age %></td>
        
        <td><%= link_to 'S', @article %></td>
        <td><%= link_to 'E', edit_article_path(@article) %></td>
        <td><%= link_to 'D', @article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

  </tbody>
</table>

<br>

<%= button_to "Nouvel article", new_article_path, :class => "button", :method => :get  %>
<%= button_to "Accueil", root_path, :class => "button", :method => :get  %>
<%= button_to "Recherche", articles_search_path, :class => "button", :method => :get  %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<!-- script pour le debut du chargement -->
  <script type="text/javascript">
  <!--
    alert('Debut du chargement de la page');
  //-->
  </script>

<a href="#" onclick="alert('Bonjour !');">JavaScript</a>
<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Titre</th>
      <th>Contenu</th>
      <th>Price</th>
      <th>Jour</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.nom.capitalize %></td>
        <td><%= article.titre.capitalize %></td>
        <td><%= article.contenu %></td>
        <td><%= article.price %></td>
        <td><%= article.jour %></td>
        <td><%= article.age %></td>
        
        <td><%= link_to 'S', article %></td>
        <td><%= link_to 'E', edit_article_path(article) %></td>
        <td><%= link_to 'D', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= button_to "Nouvel article", new_article_path, :class => "button", :method => :get  %>
<%= button_to "Accueil", root_path, :class => "button", :method => :get  %>
<%= button_to "Recherche", articles_search_path, :class => "button", :method => :get  %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/search.html.erb
<h1>Search article</h1>
<!---
<%= render 'form_search' %>
-->

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>
<%= button_to "Executer", root_path, :class => "button", :method => :get  %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Identifiant:</strong>
  <%= @article.id %>
</p>
<p>
  <strong>Nom:</strong>
  <%= @article.nom %>
</p>

<p>
  <strong>Titre:</strong>
<font color="red"><%= @article.titre %></font>
</p>

<p>
  <strong>Contenu:</strong>
  <%= @article.contenu %>
</p>
<p>
  <strong>Price:</strong>
  <%= @article.price %>
</p>
  <strong>Jour:</strong>
  <%= @article.jour %>
</p>
</p>
  <strong>Age:</strong>
  <%= @article.age %>
</p>



<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/home/index.html.erb
<h1>Le site immo</h1>
<%= link_to "Liste des articles", articles_path %> 
<%= link_to "Liste des acquéreurs", acquereurs_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Immo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>